check_server/urls.py
from django.urls import path
from .update_delete_views import (
    get_server,
    update_server,
    get_app,
    update_app,
    get_docker_info,
    update_docker_app,
    get_domain_info,
    update_domain,
)
from .views import (
    check_task,
    index,
    user_login,
    user_logout,
    camera,
    add_server,
    applications,
    add_apps,
    add_domain,
    app_info,
    add_docker,
    docker_info,
)


urlpatterns = [
    path("check", check_task),
    path("", index),
    path("login/", user_login, name="login"),
    path("logout/", user_logout, name="logout"),
    path("device", camera, name="camera"),
    path("add-server", add_server, name="add-server"),
    path("servers/<int:server_id>/", get_server, name="get-server"),
    path("servers/<int:server_id>/update/", update_server, name="update-server"),
    path("apps/<int:server_id>/", applications, name="applications"),
    path("app/<int:app_id>/", get_app, name="get-applications-info"),
    path("apps/<int:app_id>/update/", update_app, name="update-application"),
    path("add-apps", add_apps, name="add-applications"),
    path("add-domain", add_domain, name="add-domain"),
    path("add-docker", add_docker, name="add-domain"),
    path("app-info/<int:app_id>", app_info, name="app-info"),
    path("docker-info/<int:app_id>", docker_info, name="docker-info"),
    path("docker-apps/<int:app_id>/", get_docker_info, name="get-docker-info"),
    path(
        "docker-apps/<int:app_id>/update/", update_docker_app, name="update-docker-app"
    ),
    path("domains/<int:app_id>/", get_domain_info, name="get-domain"),
    path("domains/<int:app_id>/update/", update_domain, name="update-domain"),
]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("check_server.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

check_server/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Company(models.Model):

    name = models.CharField(max_length=50)
    chanel_id = models.CharField(max_length=50)
    user = models.ManyToManyField(to=User)
    date_joined = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name


class Server(models.Model):

    name = models.CharField(max_length=50)
    ssh_port = models.IntegerField(default=22)
    ipv4 = models.CharField(max_length=20)
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=150)
    company = models.ForeignKey(to=Company, on_delete=models.CASCADE)

    class Meta:

        unique_together = ["ipv4", "username"]

    def __str__(self) -> str:
        return self.name


class Application(models.Model):

    name_run_on_server = models.CharField(max_length=50)
    port = models.IntegerField(default=0)
    server = models.ForeignKey(to=Server, on_delete=models.CASCADE)
    company = models.ForeignKey(to=Company, on_delete=models.CASCADE)

    class Meta:
        ordering = ["port"]

    def __str__(self) -> str:
        return self.name_run_on_server

    class Meta:
        unique_together = ["port", "server"]


class DockerApplication(models.Model):
    name_run_on_docker = models.CharField(max_length=50)
    container_name = models.CharField(max_length=50)
    port = models.IntegerField(default=0)
    server = models.ForeignKey(to=Server, on_delete=models.CASCADE)
    company = models.ForeignKey(to=Company, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.container_name} {self.port}"

    class Meta:
        unique_together = ["port", "server", "container_name"]


class Domain(models.Model):
    domain = models.CharField(max_length=50)
    server = models.ForeignKey(to=Server, on_delete=models.CASCADE)
    company = models.ForeignKey(to=Company, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.domain

    class Meta:
        unique_together = ["server", "domain"]


class Alert(models.Model):

    time = models.DateTimeField()
    server = models.ForeignKey(to=Server, on_delete=models.SET_NULL, null=True)
    application = models.ForeignKey(
        to=Application, on_delete=models.SET_NULL, null=True
    )
    domain = models.ForeignKey(to=Domain, on_delete=models.SET_NULL, null=True)
    docker = models.ForeignKey(
        to=DockerApplication, on_delete=models.SET_NULL, null=True
    )

check_server/forms.py
import re
from typing import Any
from django import forms
from .models import Server, Application, Domain, DockerApplication
from .check_functions import is_server_alive, is_port_open, check_ssl_certificate
from .connect_server import ssh_connect


class ServerForm(forms.ModelForm):
    class Meta:
        model = Server
        fields = ["name", "ssh_port", "ipv4", "username", "password", "company"]

    def clean_ipv4(self):
        ipv4 = self.cleaned_data.get("ipv4")

        ip_pattern = r"^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$"
        if ipv4 and not re.match(ip_pattern, ipv4):
            raise forms.ValidationError("Invalid IP address format.")

        if not is_server_alive(ipv4):
            raise forms.ValidationError("Non-existent or non-working server IP address")

        return ipv4

    def clean(self) -> dict[str, Any]:

        data = super().clean()
        ipv4 = data.get("ipv4")
        username = data.get("username")
        password = data.get("password")
        port = data.get("ssh_port")
        # if not ssh_connect(ip=ipv4, username=username, password=password, port=port):
        #     raise forms.ValidationError("Incorrect username or password")
        return data


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ["name_run_on_server", "company", "server", "port"]


class DomainForm(forms.ModelForm):
    class Meta:
        model = Domain
        fields = ["domain", "company", "server"]


class DockerApplicationForm(forms.ModelForm):

    class Meta:
        model = DockerApplication
        fields = ["name_run_on_docker", "container_name", "company", "server", "port"]

check_server/views.py
from .forms import ServerForm, ApplicationForm, DomainForm, DockerApplicationForm
from django.shortcuts import render, get_object_or_404
from django.http.request import HttpRequest
from django.contrib.auth import authenticate
from django.http.response import JsonResponse
from .models import Server, Application, Company, Domain, DockerApplication
from .tasks import manitor_server, check_domain_ssl, check_docker_app
from .get_log import check_service_status, get_logs_and_performance_by_port
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from .send_telegram_notifacation import get_chat_info
from .check_functions import (
    is_server_alive,
    is_port_open,
    check_ssl_certificate,
    get_docker_ports_via_ssh,
    is_docker_port_active,
)
from .connect_server import ssh_connect, get_performance
from datetime import datetime

from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.conf import settings

# Create your views here.


@csrf_exempt
def user_login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("/")
            else:
                return render(
                    request,
                    "login.html",
                    {"form": form, "error": "Invalid username or password"},
                )
    else:
        form = AuthenticationForm()
    return render(request, "login.html", {"form": form})


def user_logout(request):
    logout(request)
    return redirect("login")


@login_required
def index(request):

    host_name = request.get_host()
    settings.DOMAIN = host_name

    name = request.GET.get("name", "")
    chat_id = request.GET.get("chanel_id", "")
    company_id = request.GET.get("company_id", "")

    user = request.user
    companies = Company.objects.filter(user=user)

    if chat_id:
        company = get_object_or_404(Company, id=company_id)
        company.chanel_id = chat_id
        company.save()

    telegram_chanel_info = []

    for company in companies:

        chanel_info = get_chat_info(company.chanel_id)
        chanel_info["company_id"] = company.pk
        chanel_info["chat_id"] = company.chanel_id
        telegram_chanel_info.append(chanel_info)

    servers = Server.objects.filter(company__in=companies, name__contains=name).values(
        "id", "name", "ipv4"
    )
    for server in servers:
        is_active = is_server_alive(server["ipv4"])
        server["is_active"] = is_active

    return render(
        request,
        "index.html",
        {"servers": servers, "name": name, "chanels": telegram_chanel_info},
    )


@csrf_exempt
@login_required
def add_server(request):
    if request.method == "POST":
        data = request.POST.copy()
        data["company"] = Company.objects.filter(user=request.user).first().pk

        form = ServerForm(data)
        del data
        if form.is_valid():
            form.save()
            return JsonResponse(
                {
                    "success": True,
                    "message": f"{form.data['name']} is successfully added!",
                }
            )
        else:
            return JsonResponse({"success": False, "message": form.errors})
    else:
        form = ServerForm()

    return render(request, "index.html", {"form": form})


@login_required
def applications(request, server_id):
    server = get_object_or_404(Server, id=server_id)

    name = request.GET.get("name", "")

    ssh = ssh_connect(server.ipv4, server.username, server.password, server.ssh_port)

    if ssh:
        performance = get_performance(ssh)
        docker_data = get_docker_ports_via_ssh(ssh)
    else:
        performance = {}

    apps = (
        Application.objects.filter(server=server, name_run_on_server__contains=name)
        .select_related("server")
        .values("id", "name_run_on_server", "port", "server__ipv4")
    )
    for app in apps:
        is_active = is_port_open(app["server__ipv4"], app["port"])
        app["is_active"] = is_active

    domains = Domain.objects.filter(server=server, domain__contains=name).values(
        "domain", "id"
    )

    docker_apps = (
        DockerApplication.objects.filter(server=server, container_name__contains=name)
        .select_related("server")
        .values("id", "name_run_on_docker", "container_name", "port")
    )

    for docker_app in docker_apps:
        is_active = is_docker_port_active(
            ssh, docker_app["port"], docker_app["container_name"]
        )
        docker_app["is_active"] = is_active

    for domain in domains:
        check = check_ssl_certificate(domain["domain"])
        is_active = check["is_valid"]
        valid_to = check["valid_to"]
        days = (check["valid_to"] - datetime.now()).days
        domain["is_valid"] = is_active
        domain["valid_to"] = valid_to
        domain["days"] = days

    context = {
        "server": server,
        "apps": apps,
        "domains": domains,
        "performance": performance,
        "docker_apps": docker_apps,
    }
    if ssh:
        ssh.close()

    return render(
        request,
        "app.html",
        context,
    )


@csrf_exempt
@login_required
def add_apps(request):
    if request.method == "POST":

        data = request.POST
        form = ApplicationForm(data)

        if form.is_valid():
            form.save()
            return JsonResponse(
                {
                    "success": True,
                    "message": f"{form.data['name_run_on_server']} is successfully added!",
                }
            )
        else:
            return JsonResponse({"success": False, "message": form.errors})
    else:
        form = Application()

    return render(request, "app.html", {"form": form})


@csrf_exempt
@login_required
def add_domain(request):
    if request.method == "POST":

        data = request.POST
        form = DomainForm(data)
        if form.is_valid():
            form.save()

            return JsonResponse(
                {
                    "success": True,
                    "message": f"{form.data['domain']} is successfully added!",
                }
            )

        else:

            return JsonResponse({"success": False, "message": form.errors})
    else:
        form = Application()

    return render(request, "apps.html", {"form": form})


@csrf_exempt
@login_required
def add_docker(request):
    if request.method == "POST":

        data = request.POST
        form = DockerApplicationForm(data)
        if form.is_valid():
            form.save()

            return JsonResponse(
                {
                    "success": True,
                    "message": f"{form.data['container_name']} is successfully added!",
                }
            )

        else:

            return JsonResponse({"success": False, "message": form.errors})
    else:
        form = Application()

    return render(request, "apps.html", {"form": form})


@login_required
def camera(request):
    return render(request, "devices.html", {})


@login_required
def app_info(request, app_id):
    app = get_object_or_404(Application, id=app_id)
    ssh = ssh_connect(
        app.server.ipv4, app.server.username, app.server.password, app.server.ssh_port
    )
    logs = check_service_status(ssh, app.name_run_on_server)
    logs["service"] = app.name_run_on_server.title()

    if ssh:
        ssh.close()

    return render(request, "log.html", logs)


@login_required
def docker_info(request, app_id):
    app = get_object_or_404(DockerApplication, id=app_id)
    ssh = ssh_connect(
        app.server.ipv4, app.server.username, app.server.password, app.server.ssh_port
    )
    logs = get_logs_and_performance_by_port(ssh, app.container_name, app.port)
    logs["performance"] = logs["performance"].split("\n")
    logs["service"] = logs.pop("image_name")
    is_active = is_docker_port_active(ssh, app.port, app.container_name)
    logs["status"] = "active" if is_active else "inactive"
    ssh.close()
    return render(request, "log.html", logs)


def check_task(request: HttpRequest):
    task = check_docker_app.delay()
    manitor_server.delay()
    check_domain_ssl.delay()
    return JsonResponse({"task": task.id})

check_server/templates/app.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Server Device Dashboard</title>
    <link rel="stylesheet" href="{% static 'styles.css'%}">
</head>
<body>

    <!-- Header section -->
    <div class="header">
        <div class="header-item">
            <a href="/">Server</a>
        </div>
        <div class="header-item">
            <a href="/device">Device</a>
        </div>
        <div class="header-item">
            <a href="/logout/">Log out</a>
        </div>
    </div>

    <!-- Search Bar -->
    <div class="search-container">
        <form action="/apps/{{ server.id }}/" method="get" class="search-container">
            {% if name %}
                <input type="text" class="search-bar" value="{{name}}" name="name" placeholder="Search">
            {% else %}
                <input type="text" class="search-bar" placeholder="Search" name="name">
            {% endif %}
            <button class="search-button">&#128269;</button>
        </form>
    </div>
    <h4 style="max-width: 800;">Server Info</h4>
    <div class="server-details">
        <ul>
            <li><strong>Server Name:</strong> {{server.name}}</li>
            <li><strong>Server IPv4:</strong> {{server.ipv4}}</li>
            <li><strong>Server Username:</strong> {{server.username}}</li>
            <li><strong>Server Password:</strong> {{server.password}}</li>
            <li><strong>Server SSH PORT:</strong> {{server.ssh_port}}</li>
        </ul>
    </div>
    <h4 style="max-width: 800;">Server Performance</h4>
    <div class="server-details">
        <ul>
            <li><strong>CPU usage</strong> {{ performance.cpu_usage }}</li>
            <li><strong>DISK usage</strong> {{ performance.disk_usage }}</li>
            <li><strong>NETWORK usage</strong> {{ performance.network_usage }}</li>
            <li><strong>RAM usage</strong> {{ performance.ram_usage }}</li>
        </ul>
    </div>

    <!-- Button to open the Apps Modal -->
    <button id="openFormBtnApp">Add Apps</button>

    <!-- Modal for Apps -->
    <div id="myModalApp" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2>Apps</h2>

            <form method="POST" id="serverForm" action="/add-apps">
                {% csrf_token %}
                <label for="id_name">Service Name :</label>
                <input type="text" name="name_run_on_server" class="form-control" id="id_name" placeholder="example: nginx" required>

                <label for="id_ipv4">Port:</label>
                <input type="text" name="port" class="form-control" id="id_ipv4" placeholder="example: 80" required>

                <input type="hidden" name="server" value={{server.id}}>
                <input type="hidden" name="company" value={{server.company.id}}>

                <button type="submit">Submit</button>
            </form>
        </div>
    </div>

    <!-- Server list -->
    <div class="server-list">
        {% for app in apps %}
            {% if app.is_active %}
                <div class="server-item green" data-link="/app-info/{{ app.id }}">
            {% else %}
                <div class="server-item red" data-link="/app-info/{{ app.id }}">
            {% endif %}
                    <span class="server-name">{{ app.name_run_on_server }}</span>
                    <span class="server-ip">{{ app.port }}</span>
                    <div class="server-actions">
                        <!-- Update button -->
                        <button class="update-btn" data-id="{{ app.id }}" data-type="app">Update</button>
                        <!-- Delete button -->
                        <button class="delete-btn" data-id="{{ app.id }}" data-type="app">Delete</button>
                    </div>
                </div>

        {% endfor %}
    </div>

    <h3 style="margin-top: 30px;">Docker Apps</h3>

    <!-- Button to open the Docker Apps Modal -->
    <button id="openFormBtnDockerApp">Add Docker Apps</button>

    <!-- Modal for Apps -->
    <div id="myModalDockerApp" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2>Apps</h2>

            <form method="POST" id="serverFormDockerApp" action="/add-docker">
                {% csrf_token %}
                <label for="id_name">Image:</label>
                <input type="text" name="name_run_on_docker" class="form-control" id="id_name" placeholder="example: nginx" required>

                <label for="id_name">Container Name:</label>
                <input type="text" name="container_name" class="form-control" placeholder="example: nginx-container" id="id_name" required>

                <label for="id_ipv4">Port:</label>
                <input type="text" name="port" class="form-control" id="id_ipv4" placeholder="example: 80" required>

                <input type="hidden" name="server" value={{server.id}}>
                <input type="hidden" name="company" value={{server.company.id}}>

                <button type="submit">Submit</button>
            </form>
        </div>
    </div>

    <!-- Server list -->
    <div class="server-list">
        
        {% for app in docker_apps %}
            {% if app.is_active %}
                <div class="server-item green" data-link="/docker-info/{{ app.id }}">
            {% else %}
                <div class="server-item red" data-link="/docker-info/{{ app.id }}">
            {% endif %}
                    <span class="server-name">{{ app.container_name }}</span>
                    <span class="server-ip">{{ app.port }}</span>
                    <div class="server-actions">
                        <!-- Update button -->
                        <button class="update-btn" data-id="{{ app.id }}" data-type="docker">Update</button>
                        <!-- Delete button -->
                        <button class="delete-btn" data-id="{{ app.id }}" data-type="docker">Delete</button>
                    </div>
                </div>
        {% endfor %}
    
    </div>

    <!-- Domains section -->
    <div class="domain-list">
        <h3>Domains</h3>
        
        <!-- Button to open the Domains Modal -->
        <button id="openFormBtnDomain">Add Domain</button>

        <!-- Modal for Domains -->
        <div id="myModalDomain" class="modal">
            <div class="modal-content">
                <span class="close">&times;</span>
                <h2>Domain</h2>

                <form method="POST" id="serverFormDomain" action="/add-domain">
                    {% csrf_token %}
                    <label for="id_name">Domain:</label>
                    <input type="text" name="domain" class="form-control" id="id_name" placeholder="example: example.com" required>

                    <input type="hidden" name="server" value={{server.id}}>
                    <input type="hidden" name="company" value={{server.company.id}}>

                    <button type="submit">Submit</button>
                </form>
            </div>
        </div>

        <div class="domain-container">
            {% for domain in domains %}
                <div class="domain-item {% if domain.is_valid %}valid{% else %} invalid {% endif %}">
                    <div class="domain-header">
                        <span class="domain-name"><strong>Domain:</strong> {{ domain.domain }}</span>
                    </div>
                    <div class="domain-body">
                        <span class="domain-valid-to"><strong>Validity Period:</strong> {{ domain.valid_to }}</span>
                        <span class="domain-days"><strong>Remaining days:</strong> {{ domain.days }}</span>
                        <span class="domain-ssl">
                            <strong>SSL:</strong> 
                            {% if domain.is_valid %}
                                Yes
                            {% else %}
                                No
                            {% endif %}
                        </span>
                    </div>
                    <div class="server-actions">
                        <!-- Update button -->
                        <button class="update-btn" data-id="{{ domain.id }}" data-type="domain">Update</button>
                        <!-- Delete button -->
                        <button class="delete-btn" data-id="{{ domain.id }}" data-type="domain">Delete</button>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <!-- Error popup (Initially hidden) -->
    <div id="errorPopup" class="error-popup">
        <!-- Error message will be inserted here -->
    </div>

    <script src="{% static 'scripts.js' %}"></script>

</body>
</html>

check_server/templates/applications.html
{% extends 'base_generic.html'%}

{% block title %}Devices{% endblock %}

<div class="server-list">
    <div class="server-item green">
        <div class="server-item red">

            <span class="server-name">Camera 1</span>
            <span class="server-ip">rtsp://username:password@host/stream</span>
    
        </div>   
        <div class="server-item green">

            <span class="server-name">Camera 2</span>
            <span class="server-ip">rtsp://username:password@host/stream1</span>
    
        </div>   
    </div>
</div>

check_server/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cradle Vision</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <!-- Header -->
    <div class="header">
        <div class="header-item">
            <a href="/">Server</a>
        </div>
        <div class="header-item">
            <a href="/device">Device</a>
        </div>
        <div class="header-item">
            <a href="/logout/">Log out</a>
        </div>
    </div>

    <!-- Content Section -->
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Footer -->
    <footer>
        <p>&copy; 2024 Cradle Vision. All rights reserved.</p>
    </footer>

</body>
</html>

check_server/templates/devices.html
{% extends 'base_generic.html'%}

{% block title %}Devices{% endblock %}

<div class="server-list">
    <div class="server-item green">
        <div class="server-item red">

            <span class="server-name">Camera 1</span>
            <span class="server-ip">rtsp://username:password@host/stream</span>
    
        </div>   
        <div class="server-item green">

            <span class="server-name">Camera 2</span>
            <span class="server-ip">rtsp://username:password@host/stream1</span>
    
        </div>   
    </div>
</div>

check_server/templates/domains.html
{% extends "base_generic.html" %}

{% block content %}
<div class="domain-list">
    <h3>Domains</h3>

    <!-- Button to open the Domains Modal -->
    <button id="openFormBtnDomain">Add Domain</button>

    <!-- Modal for Domains -->
    <div id="myModalDomain" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2>Add Domain</h2>
            <form method="POST" id="serverFormDomain" action="/add-domain">
                {% csrf_token %}
                <label for="id_name">Domain:</label>
                <input type="text" name="domain" class="form-control" id="id_name" required>
                <input type="hidden" name="server" value={{server.id}}>
                <input type="hidden" name="company" value={{server.company.id}}>
                <button type="submit">Submit</button>
            </form>
        </div>
    </div>

    <div class="domain-container">
        {% for domain in domains %}
        <div class="domain-item {% if domain.is_valid %}valid{% else %}invalid{% endif %}">
            <div class="domain-header">
                <span class="domain-name"><strong>Domain:</strong> {{ domain.domain }}</span>
            </div>
            <div class="domain-body">
                <span class="domain-valid-to"><strong>Validity Period:</strong> {{ domain.valid_to }}</span>
                <span class="domain-days"><strong>Remaining days:</strong> {{ domain.days }}</span>
                <span class="domain-ssl"><strong>SSL:</strong> 
                    {% if domain.is_valid %}
                        Yes
                    {% else %}
                        No
                    {% endif %}
                </span>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

check_server/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
{% load static %}
    <!-- Search Bar -->
    <div class="search-container">
        <form action="/" method="get" class="search-container">
            
            {% if name %}
                <input type="text" class="search-bar" value="{{name}}" name="name" placeholder="Search">
            {% else %}
                <input type="text" class="search-bar" placeholder="Search" name="name">
            {% endif %}
            <button class="search-button">&#128269;</button>
        </form>
    </div>

    <h4 style="max-width: 800;">Chanel Info</h4>
    {% for chanel in chanels %}
    <div class="server-details">
        <ul>
            <li><strong>Chanel Name:</strong> {{chanel.chat_name}}</li>
            <li><strong>Type:</strong> {{chanel.chat_type}}</li>
            <li><strong>Username:</strong> {{chanel.username}}</li>
            <li><strong>Description:</strong> {{chanel.description}}</li>
            <li><strong></strong> 
                
                <form action="" id="update-chanel">
                    <label for="id_ipv4">Chanel ID:</label>
                    <input type="number" name="chanel_id" class="form-control" id="id_ssh_port" value="{{ chanel.chat_id }}" required>
                    <input type="hidden" name="company_id" value="{{ chanel.company_id }}">
                    <button type="submit">Update</button>
                </form>
        </li>
        </ul>
    </div>
    {% endfor %}
    <!-- Button to open the modal (form) -->
    <button id="openFormBtn">Add Server</button>

    <!-- Modal (Popup) with form inside -->
    <div id="myModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2>Add Server</h2>

            <form method="POST" data-url="{% url 'add-server' %}" id="serverForm" >
                {% csrf_token %}
                <label for="id_name">Server Name:</label>
                <input type="text" name="name" class="form-control" id="id_name" required>

                <label for="id_ssh_port">SSH Port:</label>
                <input type="number" name="ssh_port" class="form-control" id="id_ssh_port" value="22" required>

                <label for="id_ipv4">IPv4 Address:</label>
                <input type="text" name="ipv4" class="form-control" id="id_ipv4" required>

                <label for="id_username">Username:</label>
                <input type="text" name="username" class="form-control" id="id_username" required>

                <label for="id_password">Password:</label>
                <input type="password" name="password" class="form-control" id="id_password" required>

                <button type="submit">Submit</button>
            </form>
        </div>
    </div>

   <!-- Server list -->
    <div class="server-list">
        {% for server in servers %}
        <div class="server-item {% if server.is_active %} green {% else %} red {% endif %}" data-link="/apps/{{ server.id }}/">
            <span class="server-name">{{ server.name }}</span>
            <span class="server-ip">{{ server.ipv4 }}</span>
            <div class="server-actions">
                <!-- Update button -->
                <button class="update-btn" data-id="{{ server.id }}">Update</button>
                <!-- Delete button -->
                <button class="delete-btn" data-id="{{ server.id }}">Delete</button>
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- Error popup (Initially hidden) -->
    <div id="errorPopup" class="error-popup">
        <!-- Error message will be inserted here -->
    </div>

    <!-- Success popup (Initially hidden) -->
    <div id="successPopup" class="success-popup">
        <!-- Success message will be inserted here -->
    </div>

    <script src="{% static 'index.js' %}"></script>
{% endblock %}